name: 'test'
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: test
        run: npm run test
